# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 825a6bcfbb8d2a47591af1841464afdeacaee598e2d21a00e820f19b2b474a31200b055125a0023a8b71d77a587f28083fc16f6961fc9aa2baa147daf7af52eb

test:
  secret_key_base: 53515c18e676a0577587aa7bf1fddacdfb82c728429d9ab37302cb7b074eb3ae0e00abf5c5008baf8d8888ff390efb8a09b74841fc0206c3d1d7b9220405ba15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
